Fix subscription change in trial (#62)
### What this PR does

* Added the `trial_end` now whenever changing the plan for an org
* This happens when we change the customer's plan
* Kinvey ran into this

### Changing of tests without code change

```
  #stripe.invoice.created Integration Test
    1) should update the plan for the organization based on current usage
    ✓ should update the invoice with the payment method owner and mark it as paid (1172ms)


  1 passing (6s)
  1 failing

  1) #stripe.invoice.created Integration Test should update the plan for the organization based on current usage:

      AssertionError: expected 'trialing' to equal 'active'
      + expected - actual

      -trialing
      +active
```

### Commits

* Make sure subscription change doesn't put customer in trial
* Adding to integration tests
* convert + to parseInt